<MunuScreen>:
    canvas.before:
        Color:
            rgba: 1,1,0,1
        Rectangle:
            pos:self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'
        Label:
            id: title_game
            text:'Some Clicker'
            font_name: 'assets/RubikScribble-Regular.ttf'
            color: '#4424D6'
            font_size: '40sp'